version: '3.8'

services:
  springboot-app:
    image: fashionservice:latest
    container_name: springboot_container
    build:
      context: ./fashionService
      dockerfile: Dockerfile
    ports:
      - "8077:8077"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fashiondesign
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - my-network
    depends_on:
      - mysql
      - frontend-angular
    restart: always

  frontend-angular:
    image: angularfrontend:latest
    container_name: angular_container
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: fashiondesign
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:


