version: '3.8'

services:
  springboot-app:
    image: fashionservice:latest
    container_name: springboot_container
    build:
      context: ./fashionService
      dockerfile: Dockerfile
    ports:
      - "8077:8077"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fashiondesign
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: FashionDesign@123
    networks:
      - my-network
    depends_on:
      - mysql
      - frontend-angular

  frontend-angular:
    image: angularfrontend:latest
    container_name: angular_container
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: FashionDesign@123  # Set the root password
      MYSQL_DATABASE: fashiondesign  # Optional: Initialize a database
    ports:
      - "3309:3306"  # Map host port 3309 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
